--[[
    Icewrack Status Effects

]]

IW_STATUS_EFFECT_NONE = 0
IW_STATUS_EFFECT_STUN = 1
IW_STATUS_EFFECT_SLOW = 2
IW_STATUS_EFFECT_SILENCE = 3
IW_STATUS_EFFECT_ROOT = 4
IW_STATUS_EFFECT_HEX = 5
IW_STATUS_EFFECT_DISARM = 6
IW_STATUS_EFFECT_SLEEP = 7
IW_STATUS_EFFECT_FROZEN = 8
IW_STATUS_EFFECT_CHILLED = 9
IW_STATUS_EFFECT_WET = 10
IW_STATUS_EFFECT_BURNING = 11
IW_STATUS_EFFECT_POISON = 12
IW_STATUS_EFFECT_BLEED = 13
IW_STATUS_EFFECT_BLIND = 14
IW_STATUS_EFFECT_PETRIFY = 15
IW_STATUS_EFFECT_INVISIBLE = 16
IW_STATUS_EFFECT_HASTED = 17
IW_STATUS_EFFECT_FLYING = 18
IW_STATUS_EFFECT_SHIELDED = 19
IW_STATUS_EFFECT_EMPOWERED = 20
IW_STATUS_EFFECT_INVULNERABLE = 21
IW_STATUS_EFFECT_ANY = 22		--Do not use this; this is only for the AAM